import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import notesRouter from "./notes";
import pdfsRouter from "./pdfs";
import booksRouter from "./books";
import quizzesRouter from "./quizzes";
import communityRouter from "./community";
import announcementsRouter from "./announcements";
import progressRouter from "./progress";
import bookmarksRouter from "./bookmarks";
import calendarRouter from "./calendar";
import dashboardRouter from "./dashboard";
import uploadRouter from "./upload";
import feedbackRouter from "./feedback";
import leaderboardRouter from "./leaderboard";
import doubtsRouter from "./doubts";
import aiDoubtRouter from "./aiDoubt";
import superAdminRouter from "./superAdmin";
import pushRouter from "./push";
import youtubeRouter from "./youtube";
import soundcloudRouter from "./soundcloud";
import { flashcardsRouter } from "./flashcards";
import { mnemonicsRouter } from "./mnemonics";
import { studySessionsRouter } from "./studySessions";
import { examsRouter } from "./exams";
import { confessionsRouter } from "./confessions";
import { studyRoomsRouter } from "./studyRooms";
import { aiToolsRouter } from "./aiTools";
import { activityFeedRouter } from "./activityFeed";
import { moderationRouter } from "./moderation";
import { warningsRouter } from "./warningsRoute";
import { auditLogsRouter } from "./auditLogsRoute";
import { noticesRouter } from "./notices";
import { quizIntelligenceRouter } from "./quizIntelligence";
import { adminContentRouter } from "./adminContent";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/notes", notesRouter);
router.use("/pdfs", pdfsRouter);
router.use("/books", booksRouter);
router.use("/quizzes", quizzesRouter);
router.use("/quiz-attempts", (req, res, next) => {
  req.url = "/attempts/my";
  quizzesRouter(req, res, next);
});
router.use("/community", communityRouter);
router.use("/announcements", announcementsRouter);
router.use("/progress", progressRouter);
router.use("/bookmarks", bookmarksRouter);
router.use("/calendar", calendarRouter);
router.use("/dashboard", dashboardRouter);
router.use("/upload", uploadRouter);
router.use("/feedback", feedbackRouter);
router.use("/leaderboard", leaderboardRouter);
router.use("/doubts", doubtsRouter);
router.use("/doubts", aiDoubtRouter);
router.use("/super-admin", superAdminRouter);
router.use("/push", pushRouter);
router.use("/youtube", youtubeRouter);
router.use("/soundcloud", soundcloudRouter);
router.use("/flashcards", flashcardsRouter);
router.use("/mnemonics", mnemonicsRouter);
router.use("/study-sessions", studySessionsRouter);
router.use("/exams", examsRouter);
router.use("/confessions", confessionsRouter);
router.use("/study-rooms", studyRoomsRouter);
router.use("/ai", aiToolsRouter);
router.use("/admin/activity-feed", activityFeedRouter);
router.use("/admin/moderation", moderationRouter);
router.use("/admin/warnings", warningsRouter);
router.use("/admin/audit-logs", auditLogsRouter);
router.use("/admin/notices", noticesRouter);
router.use("/admin/quiz-intelligence", quizIntelligenceRouter);
router.use("/admin/content", adminContentRouter);

export default router;
