import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import notesRouter from "./notes";
import pdfsRouter from "./pdfs";
import booksRouter from "./books";
import quizzesRouter from "./quizzes";
import communityRouter from "./community";
import announcementsRouter from "./announcements";
import progressRouter from "./progress";
import bookmarksRouter from "./bookmarks";
import calendarRouter from "./calendar";
import dashboardRouter from "./dashboard";
import uploadRouter from "./upload";
import feedbackRouter from "./feedback";
import leaderboardRouter from "./leaderboard";
import doubtsRouter from "./doubts";
import aiDoubtRouter from "./aiDoubt";
import superAdminRouter from "./superAdmin";
import pushRouter from "./push";
import youtubeRouter from "./youtube";
import { flashcardsRouter } from "./flashcards";
import { mnemonicsRouter } from "./mnemonics";
import { studySessionsRouter } from "./studySessions";
import { examsRouter } from "./exams";
import { confessionsRouter } from "./confessions";
import { studyRoomsRouter } from "./studyRooms";
import { vivaRoomsRouter } from "./vivaRooms";
import { aiToolsRouter } from "./aiTools";
import { practicalHubRouter } from "./practicalHub";
import { vivaSourcesRouter } from "./vivaSources";
import { anatomyVivaImagesRouter } from "./anatomyVivaImages";
import { activityFeedRouter } from "./activityFeed";
import { moderationRouter } from "./moderation";
import { warningsRouter } from "./warningsRoute";
import { auditLogsRouter } from "./auditLogsRoute";
import { noticesRouter } from "./notices";
import { quizIntelligenceRouter } from "./quizIntelligence";
import { adminContentRouter } from "./adminContent";
import { gamesRouter } from "./games";
import { quizSubmissionsRouter } from "./quizSubmissions";
import { proctoringRouter } from "./proctoring";
import { xpRouter } from "./xp";
import { anatomyAIRouter } from "./anatomyAI";
import pyqsRouter from "./pyqs";
import { meddyRouter } from "./meddy";
import { submissionsRouter } from "./submissions";
import { deviceAnalyticsRouter } from "./deviceAnalytics";
import { appUpdatesRouter } from "./appUpdates";
import { analyticsRouter } from "./analytics";
import { clinicalCasesRouter } from "./clinicalCases";
import { revisionItemsRouter } from "./revisionItems";
import { grandTestsRouter } from "./grandTests";
import { customQuizRouter } from "./customQuiz";
import { photoDoubtRouter } from "./photoDoubt";
import { notesMarketplaceRouter } from "./notesMarketplace";
import { grandRoundsRouter } from "./grandRounds";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/notes", notesRouter);
router.use("/pdfs", pdfsRouter);
router.use("/books", booksRouter);
router.use("/quizzes", quizzesRouter);
router.use("/quiz-attempts", (req, res, next) => {
  req.url = "/attempts/my";
  quizzesRouter(req, res, next);
});
router.use("/community", communityRouter);
router.use("/announcements", announcementsRouter);
router.use("/progress", progressRouter);
router.use("/bookmarks", bookmarksRouter);
router.use("/calendar", calendarRouter);
router.use("/dashboard", dashboardRouter);
router.use("/upload", uploadRouter);
router.use("/feedback", feedbackRouter);
router.use("/leaderboard", leaderboardRouter);
router.use("/doubts", doubtsRouter);
router.use("/doubts", aiDoubtRouter);
router.use("/super-admin", superAdminRouter);
router.use("/push", pushRouter);
router.use("/youtube", youtubeRouter);
router.use("/flashcards", flashcardsRouter);
router.use("/mnemonics", mnemonicsRouter);
router.use("/study-sessions", studySessionsRouter);
router.use("/exams", examsRouter);
router.use("/confessions", confessionsRouter);
router.use("/study-rooms", studyRoomsRouter);
router.use("/viva-rooms", vivaRoomsRouter);
router.use("/ai", aiToolsRouter);
router.use("/practical-hub", practicalHubRouter);
router.use("/admin/viva-sources", vivaSourcesRouter);
router.use("/anatomy-viva-images", anatomyVivaImagesRouter);
router.use("/admin/activity-feed", activityFeedRouter);
router.use("/admin/moderation", moderationRouter);
router.use("/admin/warnings", warningsRouter);
router.use("/admin/audit-logs", auditLogsRouter);
router.use("/admin/notices", noticesRouter);
router.use("/admin/quiz-intelligence", quizIntelligenceRouter);
router.use("/admin/content", adminContentRouter);
router.use("/games", gamesRouter);
router.use("/quiz-submissions", quizSubmissionsRouter);
router.use("/admin/quiz-submissions", quizSubmissionsRouter);
router.use("/proctoring", proctoringRouter);
router.use("/xp", xpRouter);
router.use("/anatomy", anatomyAIRouter);
router.use("/pyqs", pyqsRouter);
router.use("/meddy", meddyRouter);
router.use("/submissions", submissionsRouter);
router.use("/admin/submissions", submissionsRouter);
router.use(deviceAnalyticsRouter);
router.use("/app-updates", appUpdatesRouter);
router.use("/analytics", analyticsRouter);
router.use("/clinical-cases", clinicalCasesRouter);
router.use("/admin/clinical-cases", clinicalCasesRouter);
router.use("/revision-items", revisionItemsRouter);
router.use("/grand-tests", grandTestsRouter);
router.use("/quizzes", customQuizRouter);
router.use("/photo-doubt", photoDoubtRouter);
router.use("/marketplace/notes", notesMarketplaceRouter);
router.use("/admin/marketplace/notes", notesMarketplaceRouter);
router.use("/grand-rounds", grandRoundsRouter);
router.use("/admin/grand-rounds", grandRoundsRouter);

export default router;
